<!DOCTYPE html>
<html lang="en" style="font-size: 14px">
<head>

    <title>O jeito mais eficiente de resgatar seus clientes! | Giver</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <?php App\Models\Includes::system('head');?>

</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

<!-- PRE LOADER -->
<section class="preloader">
    <div class="spinner">

        <span class="spinner-rotate"></span>

    </div>
</section>

<!-- MENU -->
<section class="navbar custom-navbar navbar-fixed-top" role="navigation">
    <div class="container">

        <?php App\Models\Includes::system('header');?>

    </div>
</section>

<section>
    <div class="container">
        <div class="text-center">
            <h1><?php echo $_GET['customer'];?></h1>
            <br><br>
        </div>
        <?php
        $customers = new \App\Models\Customers(\App\Init::getDb());
        $list = $customers->list();
        if (!$customers->catch){
            if($list){
                ?>
                <div class="col-xs-6 col-sm-4 col-md-4">
                </div>
                <div class="col-xs-6 col-sm-4 col-md-4">
                    <table class="table table-striped table-dark">
                        <thead>
                            <tr>
                                <th class="text-center" scope="col">
                                    <?php
                                    if($_GET['customer'] == 'email'){
                                        echo 'valid';
                                    }else{
                                        ?>With<?php
                                    }?>
                                </th>
                                <th class="text-center" scope="col">
                                    <?php
                                    if($_GET['customer'] == 'email'){
                                        echo 'invalid';
                                    }else{
                                        ?>WithOut<?php
                                    }?>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($list as $row):
                                ?>
                                <tr>
                                    <th class="text-center" scope="row"><?php
                                        if($_GET['customer'] == 'email'){
                                            echo $row['valid'];
                                        }else{
                                            echo $row['NotEmpty'];
                                        }?>
                                    </th>
                                    <td class="text-center"><?php
                                        if($_GET['customer'] == 'email'){
                                            echo $row['invalid'];
                                        }else{
                                            echo $row['Isempty'];
                                        }?>
                                    </td>
                                </tr>
                            <?php
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                </div>
                <?php
            }else{
                ?>
                <div class="row fa-border alert-danger text-center">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        nenhum resultado encontrado
                    </div>
                </div>
                <?php
            }
        }else{
            ?>
            <div class="row fa-border alert-danger text-center">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <?php echo $customers->catch;?>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
</section>

<!-- SCRIPTS -->
<?php App\Models\Includes::system('scripts');?>

</body>
</html>