<!DOCTYPE html>
<html lang="en" style="font-size: 14px">
<head>

    <title>O jeito mais eficiente de resgatar seus clientes! | Giver</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <?php App\Models\Includes::system('head');?>

</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

<!-- PRE LOADER -->
<section class="preloader">
    <div class="spinner">

        <span class="spinner-rotate"></span>

    </div>
</section>

<!-- MENU -->
<section class="navbar custom-navbar navbar-fixed-top" role="navigation">
    <div class="container">

        <?php App\Models\Includes::system('header');?>

    </div>
</section>

<section>
    <div class="container">
        <div class="text-center">
            <?php
            if (!isset($this->view->error) && !isset($this->view->success) && !isset($this->view->info)){
                ?><h1><?php echo 'Upload .csv'?></h1><?php ;
            }
            else{
                if(isset($this->view->info) && !empty($this->view->info)) {
                    ?><p class="alert-info"><?php echo $this->view->info?></p><?php ;
                }else{
                    if(isset($this->view->error) && !empty($this->view->error)){
                        ?><p class="alert-danger"><?php echo $this->view->error?></p><?php ;
                    }
                    if(isset($this->view->success) && !empty($this->view->success)) {
                        ?><p class="alert-success"><?php echo $this->view->success?></p><?php ;
                    }
                }
            }
            ?>
            <br><br>
        </div>
        <form class="form-group" enctype="multipart/form-data" method="POST">
            <input type="file" name="files[]" multiple="multiple" required><br><br>
            <input class="btn btn-primary" name="load" type="submit" value="Load">
        </form>
    </div>
</section>

<!-- SCRIPTS -->
<?php App\Models\Includes::system('scripts');?>

</body>
</html>